# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  resolvers:
    default:
      web_path: ~

  filter_sets:
    cache: ~

    admin_thumbnails:
      quality: 75

      filters:
        thumbnail: { size: [80, 80], mode: outbound }

    product_thumbnails:
      quality: 85

      filters:
        thumbnail: { size: [200, 200], mode: outbound }

    avatar_thumbnails:
      quality: 90

      filters:
        thumbnail: { size: [100, 100], mode: outbound }

    avatar2_thumbnails:
      quality: 100

      filters:
        thumbnail: { size: [300, 300], mode: outbound }

    carousel:
      quality: 85

      filters:
        thumbnail: { size: [268, 268], mode: outbound }
