language: php
sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
    # Test the latest stable release
    - php: 7.3
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - ./vendor/bin/simple-phpunit install
  - composer require sensiolabs/security-checker
  - echo "DATABASE_URL=mysql://root:@127.0.0.1:3306/cocorico" | tee .env.test.local .env.local
  - ./bin/console doctrine:database:create
  - ./bin/console doctrine:migrations:migrate --no-interaction
  - ./bin/console doctrine:fixtures:load --no-interaction

script:
  - composer validate --strict --no-check-lock
  - ./bin/console lint:yaml config --parse-tags
  - ./bin/console lint:twig templates --env=prod
  - ./bin/console lint:xliff translations
  - ./bin/console security:check
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
